#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
#xmodmap "~/.Xmodmap"

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# X options
xhost + &
xset s off
xset -dpms
/usr/bin/numlockx on

# Custom desktop scripts
#/etc/mps/scripts/start_panels.sh &
#/etc/mps/scripts/start_monitors.sh &
#/etc/mps/scripts/start_windowsvm.sh &
fbsetbg ~/.config/images/wallpaper.jpg &

# Start fluxbox
exec tilda &
exec tint2 &
exec fluxbox -log "~/.fluxbox/log"
